### ISSUE TITLE
Hello, I compiled in VS2015 and VS2019, but the Demo can’t be started. I saw that there is problem with AddFunction. Could please fix it? Thanks!

### ISSUE THREAD

**Issue by kaifuzi** [mastersign/Mastersign.Expressions#1]

**Comment by mastersign** [comment]
366ac468d2c699b4fa6295697c94665c563fe987 is a quick fix. If I can find the time, I will upgrade this project to .NET Standard 2.0. I am interested in your experiences with this project. Maybe give me a brief summary (dev@mastersign.de) of your project and if you could use Mastersign.Expressions successfully.

**Comment by kaifuzi** [comment]
@mastersign Thanks very much for your quick fixing action! Yesterday I took sometime to try to fix it, but failed... If you have time, could you please change verison nubmer and update NuGet?
https://www.nuget.org/packages/Mastersign.Expressions
And I will send a e-mail to you to explain why I want to try this greate project.

**Comment by mastersign** [comment]
Released version 0.5.0 on nuget. Please take note of the changed root namespace: Mastersign.Expressions.
