### ISSUE TITLE
Option to ignore case

### ISSUE THREAD

**Issue by kaifuzi** [mastersign/Mastersign.Expressions#10]
Is it possible to add an option to ignore case?
For example, no matter user typing "IF", "If" or "if", the expression can be executed.

**Comment by mastersign** [comment]
This would require a considerable amount of work. I can't give this a priority at this time.

**Comment by kaifuzi** [comment]
I see, it will be awesome if you can improve this.

**Comment by mastersign** [comment]
Can you verify, that the implementation in branch `ignore-case` is what you wished for?

Changes: 775766e8e9bdd53155be16bbbf9b2d1472d9b5c0, 8764eee0335f2c9891cf633a1146c3910e0bb936

**Comment by kaifuzi** [comment]
@mastersign I download branch `ignore-case` and test, this is real what I want, and the properites which you provide are more than I expect! Could you please release this verison and update Nuget package?

**Comment by mastersign** [comment]
Released in version 0.5.2.
