### ISSUE TITLE
System.Windows.Forms is still missing in Demo project

### ISSUE THREAD

**Issue by kaifuzi** [mastersign/Mastersign.Expressions#12]
I tested in the latest project, but the reference "System.Windows.Forms" is still missing:
![image](https://user-images.githubusercontent.com/30330327/119528739-bfb9fc80-bd81-11eb-8d86-0a6cd35941cc.png)
I need to add "System.Windows.Forms" manually, then I can compile demo project.

_Originally posted by @kaifuzi in https://github.com/mastersign/Mastersign.Expressions/issues/5#issuecomment-847988149_

**Comment by mastersign** [comment]
Are you opening the demo project in VS2015, VS2017 or VS2019?

**Comment by mastersign** [comment]
To be clear about this, the solution with the source code, including the demo project, is intended to work with VS2019. I can not test it with older VS versions. But I want to make sure, the Nuget package can be consumed from VS2015 and VS2017 as well.

In VS2019, the demo project looks like this:
![grafik](https://user-images.githubusercontent.com/3414349/119614165-7b644600-bded-11eb-9ff9-b3dda896c19d.png)

**Comment by kaifuzi** [comment]
I have VS2015 and VS2019. I can open this project in VS2019, VS2015 can't open this project. And the library from NuGet can works well in VS2015 and VS2019 project.
In my VS2019, System.Windows.Forms is still missing in Demo project, I don't know why is different with you:
![image](https://user-images.githubusercontent.com/30330327/119624546-917fff80-be09-11eb-9d4b-f94d8403f913.png)

**Comment by mastersign** [comment]
Can you please try, if this is working?

~~~xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
	
	<PropertyGroup>
		<TargetFramework>net461</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<LangVersion>9.0</LangVersion>
		<OutputType>WinExe</OutputType>
		<PlatformTarget>AnyCPU</PlatformTarget>

		<Version>0.5.1.0</Version>

		<Title>Mastersign.Expressions Demo</Title>
		<Product>Mastersign.Expressions</Product>
		<Description>A demo application for Mastersign.Expressions.</Description>
		<Authors>Tobias Kiertscher</Authors>
		<Copyright>Copyright © Tobias Kiertscher 2021</Copyright>

	</PropertyGroup>
	
	<ItemGroup>
	  <ProjectReference Include="..\Mastersign.Expressions\Mastersign.Expressions.csproj" />
	</ItemGroup>
	
	<ItemGroup>
	  <EmbeddedResource Update="MainForm.resx" />
	</ItemGroup>

</Project>
~~~

**Comment by kaifuzi** [comment]
With your code, it works! System.Windows.Forms is loaded automatically in Demo project.
Is it because of OutputType?

**Comment by mastersign** [comment]
Either that or the changed SDK.
