### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by kaifuzi** [mastersign/Mastersign.Expressions#13]
Haha, ist is Deutsch:
![image](https://user-images.githubusercontent.com/30330327/119722329-7beff180-be6c-11eb-9cad-611bed24f0c5.png)

**Comment by mastersign** [comment]
If you are interested in such details, I would like you to check out my project [Bench](https://github.com/winbench) https://winbench.org 😏 I bet you can find a lot of such little mistakes and typos there!

But seriously, thank you for pointing such mistakes out to me.

**Comment by kaifuzi** [comment]
I will take a look the Bench, and learn how to use it.
And very welcome, maybe I focus on details too much, it's not good for daily life...

**Comment by mastersign** [comment]
@kaifuzi You mentioned, you live in Germany too. Maybe these videos could help you get a grasp of Bench: https://www.mastersign.de/bench (my first modest attempt to produce YouTube videos)

**Comment by kaifuzi** [comment]
@mastersign Although I live in Germany, my German is still not good for now... But it's also a chance to improve my German skill.
