### ISSUE TITLE
Add function CONCAT for concatenating string

### ISSUE THREAD

**Issue by kaifuzi** [mastersign/Mastersign.Expressions#23]
Is it possible to add function `concat` for concatenating string to follow Excel expression concept?
![image](https://user-images.githubusercontent.com/30330327/121588524-4cc5ac80-ca36-11eb-9067-7815531c7fbd.png)

**Comment by mastersign** [comment]
Strings can be concatenated by using the `&` operator: `"1" & "2" & "3"` → `"123"`.
If you need the function syntax, you can always add your own concat function to your evaluation context. (Look for _custom function_ in the [example](https://github.com/mastersign/Mastersign.Expressions/blob/master/docs/Example.md#example).
