### ISSUE TITLE
LoadLogicPackage Question

### ISSUE THREAD

**Issue by kaifuzi** [mastersign/Mastersign.Expressions#4]
"new FunctionHandle" is it necessary in LoadLogicPackage? I removed "new FunctionHandle", it works well too. Thanks!
`AddFunction("not", new FunctionHandle(typeof(Logic).GetMethod("Not", new[] { typeof(bool) })));`

**Comment by mastersign** [comment]
You are right, the implicit cast from `MethodInfo` to `FunctionHandle` is taking care of the instantiation.
