### ISSUE TITLE
Mastersign.Expressions.Demo issue

### ISSUE THREAD

**Issue by kaifuzi** [mastersign/Mastersign.Expressions#5]
In Mastersign.Expressions.Demo project, The reference "System.Windows.Forms" is missing, I can't compile Demo project without "System.Windows.Forms".

**Comment by mastersign** [comment]
I have converted the demo project into an sdk-style project to be future-proof for .NET >=5 and to be able to use C# 9 features. The directive `<UseWindowsForms>true</UseWindowsForms>` instructs the MSBuild system to reference the Windows Forms assemblies.

**Comment by kaifuzi** [comment]
I tested in the latest project, but the reference "System.Windows.Forms" is still missing:
![image](https://user-images.githubusercontent.com/30330327/119528739-bfb9fc80-bd81-11eb-8d86-0a6cd35941cc.png)
I need to add "System.Windows.Forms" manually, then I can compile demo project.
