### ISSUE TITLE
Version 0.5.0 doesn't support VS2015?

### ISSUE THREAD

**Issue by kaifuzi** [mastersign/Mastersign.Expressions#7]
I can load  Mastersign.Expressions 0.5.0 from NuGet in VS2019.
But I can't load it in VS2015, doesn't it support VS2015? Thanks!
Error: Could not install package 'Mastersign.Expressions 0.5.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by mastersign** [comment]
I published the package with the TFM `netstandard2.0` in the impression, .NET 4.6.1 is compatible with .NET Standard 2.0 packages.
But this seems to be only partially true: <https://stackoverflow.com/questions/46788323>.

I will add the TFM `net461` to the package. Please give me feedback, if the version 0.5.1, once it is published, is working in VS2015.

**Comment by mastersign** [comment]
Version 0.5.1 is published.

**Comment by kaifuzi** [comment]
There are still two errors when I open in VS2015:
error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.
error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

**Comment by kaifuzi** [comment]
I test version 0.5.1 with VS2015 project, it works well now, thanks!
